@port ={{$dotenv PORT}}
@baseUrl=http://localhost:{{port}}

### Search for Airpods
GET {{baseUrl}}/api/search?product=airpods

### Search for iPhone
GET {{baseUrl}}/api/search?product=iphone



### Add a new product
POST {{baseUrl}}/api/products HTTP/1.1
Content-Type: application/json

{
  "title": "bu",
  "vendor": "hu",
  "price": "hu"
    
}

### Search for product in mongodb
GET {{baseUrl}}/api/products